import {readFile,writeFile} from 'node:fs/promises';
const root=new URL('../',import.meta.url),base=new URL('results/coding/',root);
const m=JSON.parse(await readFile(new URL('manifest.json',base),'utf8'));
if(m.runs.length!==27||!m.completedAt)throw Error('Coding cohort incomplete');
const median=a=>{const s=a.filter(Number.isFinite).sort((a,b)=>a-b),n=s.length;return n?n%2?s[(n-1)/2]:(s[n/2-1]+s[n/2])/2:null;};
const fields=['modelRequests','inputTokens','outputTokens','cacheHitTokens','localWallMs','modelWallMs','mcpCalls','surfacedResultBytes'];
const groups=m.moduleCounts.flatMap(count=>m.paths.map(mode=>{const rows=m.runs.filter(r=>r.count===count&&r.mode===mode);return {count,mode,tasks:rows.length,passed:rows.filter(r=>r.passed).length,medians:Object.fromEntries(fields.map(f=>[f,median(rows.map(r=>r.metrics[f]))])),ranges:Object.fromEntries(fields.map(f=>[f,[Math.min(...rows.map(r=>r.metrics[f]).filter(Number.isFinite)),Math.max(...rows.map(r=>r.metrics[f]).filter(Number.isFinite))]]))};}));
const passed=m.runs.filter(r=>r.passed).length;
const summary={tasks:27,passed,retainedCalibration:m.priorAttempts.length,aggregation:'median of all three primary tasks per group, including real task failures; host discovery format calibration excluded and separately retained',groups};
await writeFile(new URL('summary.json',base),JSON.stringify(summary,null,2));
await writeFile(new URL('metrics.csv',base),['id,count,repeat,mode,passed,'+fields.join(','),...m.runs.map(r=>[r.id,r.count,r.repeat,r.mode,r.passed,...fields.map(f=>r.metrics[f]??'')].join(','))].join('\n')+'\n');
const names={codemode:'Codemode',ptc:'全量 DSH PTC',hybrid:'融合'};
const rows=groups.map(g=>`| ${g.count} | ${names[g.mode]} | ${g.passed}/3 | ${g.medians.modelRequests} | ${g.medians.inputTokens} | ${(g.medians.localWallMs/1000).toFixed(2)} |`);
const get=(count,mode)=>groups.find(g=>g.count===count&&g.mode===mode);
const winners=m.moduleCounts.map(count=>[count,[...m.paths].sort((a,b)=>get(count,a).medians.localWallMs-get(count,b).medians.localWallMs)[0]]);
const totals=m.paths.map(mode=>`${names[mode]} ${m.runs.filter(r=>r.mode===mode&&r.passed).length}/9`).join('，');
const requestRange=[Math.min(...m.runs.map(r=>r.metrics.modelRequests)),Math.max(...m.runs.map(r=>r.metrics.modelRequests))];
const failed=m.runs.filter(r=>!r.passed);
const failureText=failed.length?failed.map(r=>`- ${r.id}：${r.metrics.modelRequests}轮、${r.metrics.inputTokens??'未知'}输入token；独立验收${r.validation.independent.build.exitCode===0?'行为不通过':'编译不通过'}，仍有${r.validation.independent.oldApiPaths.length}个模块含旧API，观察到的通过测试结果为${r.validation.hasObservedPass?'有':'无'}。`).join('\n'):'所有任务通过独立验收。';
const text=`\n## 补充：编码任务会改变比较结果\n\n订单实验把筛选规则写得很明确，主要测工具发现和程序内的数据处理。编码时，模型必须看到足够的源码和诊断信息才能决定如何修改；运行时精简输出过度，也可能损害正确性。因此，再补一个可编译、有独立验收的跨文件 API 迁移任务，观察编排机制在编码闭环里的表现。\n\n### 从真实源码改动到独立验收\n\n任务把 TypeScript 项目中全部 \`client.request(url, options)\` 迁移为 \`client.send({url, ...options})\`。新版客户端契约已经提供。每个模块有两个调用点，包含内联参数和复用 options 两种形式；必须保留请求路径、方法、请求体、超时、响应变换及异常传播。项目规模为3、8、16个模块，即6、16、32个调用点。\n\n三条路径使用同一个 stdio MCP 服务，只提供五个文件/测试工具：list_files、search_text、read_file、replace_text、run_tests。每个任务从相同源码快照创建一个新的独立目录；宿主限制项目工具并发为8，同一文件编辑串行。模型不拿到固定修改脚本，不规定编码步骤或请求轮数，允许反复读、改、测。融合有一个发现调用的交接协议，后续编程轮数自主决定。每个编码执行阶段最多24轮模型请求，融合额外允许一个发现请求；本次融合实际最多10轮，没有触及预算。这个上限是实验预算，不是各路径的理论极限。\n\nrun_tests 先用固定 TypeScript 5.9.3 编译，再执行宿主保存的行为测试。每个模块有四项检查，覆盖正常请求及响应变换、health返回值、异常对象传播和超时参数。客户端、配置和测试不能通过项目工具修改。最终验收还会在模型结束后重新编译、测试，并核对保护文件；成功要求模型实际调用过测试并观察到通过结果。所有原始源码、最终源码、补丁调用、请求和验收结果都已保存。\n\n这是一个具有实际源码编辑、类型检查和运行时行为验证的**合成小项目**，仍然没有大型真实仓库的依赖复杂度、定位歧义和非重复代码，不能代表通用编码能力排名。项目工具的可见范围是控制边界，本实验没有验证任意模型生成代码的完整安全隔离能力。\n\n### 27个任务的结果\n\n每个规模、每条路径重复三次，总计27个任务，${passed}个通过；${totals}。表中为每组全部三次任务的中位数，**真实任务失败也计入耗时和输入量**。用量来自实际API usage，input包含缓存命中，不等同于账单。端到端耗时包含模型、工具、执行器初始化和运行器内的终检，不含项目创建、以及矩阵外层的第二次验收。\n\n| 模块数 | 路径 | 成功 | 模型请求轮数 | 输入 token | 耗时秒 |\n|---|---|---:|---:|---:|---:|\n${rows.join('\n')}\n\n**PTC“两轮完成”和“稳定更快”不能从订单任务推广到编码任务。** 本次编码任务的实际请求数为${requestRange[0]}–${requestRange[1]}轮；各规模耗时中位数最低的路径分别是${winners.map(([count,mode])=>count+'模块 '+names[mode]).join('，')}。读源码、编辑和根据诊断修正需要新的模型决策；一段程序可以合并已知操作，但不能预先替代全部后续推理。\n\n这次融合在三个规模下都取得最低的输入量和耗时中位数，并通过9/9任务；这是本次配置的观测结果。**不能把优势归因于工具发现本身**：工具目录没有缩小，SDK、提示与交接历史会影响模型的后续编排策略。

**融合在这里没有大工具目录可以裁剪。** 编码目录只有五个工具，而发现阶段选择了全部五个，融合和全量 DSH PTC的SDK相同。因此新增发现轮和历史消息是开销，不能把订单场景中“60工具只用3个”的输入收益照搬过来；最终快慢还受模型是否批量修改、是否重复输出源码和是否陷入错误修复循环影响。\n\n**先看验收成功，再看资源开销。** 同一个执行器也可能产生完全不同的调用策略，这次保留了未完成迁移的任务，没有把失败重跑到成功后覆盖。\n\n${failureText}\n\n两次3模块的PTC失败中，源码和搜索结果已正常进入模型，但模型反复检索，没有执行编辑；一次16模块失败中，模型按错误的模块规律构造替换文本，反复收到oldText不存在，留下8个模块的旧调用。这些是当前模型、提示和预算下的失败，不能解释为官方PTC执行器普遍不适合编码。

### 校准、边界与复现\n\n宿主交接最初只接受 selectedTools 字符串数组，但模型有时返回发现到的工具对象数组。宿主随后兼容顶层数组或 selectedTools 数组，并仅提取对象已有的name；不添加或替换工具、不改写模型的程序或发现结果，也保留原始返回中的声明文本及其后续输入成本。${m.priorAttempts.length}次完整的格式交接失败作为校准附件保留，提示内容和业务任务没有因此修改；已成功任务没有重跑。真实业务失败留在正式27个任务中，不自动重试。中断未完成的运行不形成完整任务记录，也未计入这27个任务的统计。\n\n这组结果没有冷缓存隔离，重复顺序虽轮换，但缓存和在线服务波动仍有影响；每格只有三次，不能证明稳定排名。SDK、包装契约、初始消息、提示和执行器不同，因此也不是只改变某一个变量的因果实验。PTC使用官方Node沙箱的read-only策略，但项目文件修改通过宿主MCP工具执行；Windows的部分文件沙箱提示原样进入模型，亦可能影响行为。Pi的peakSubmittedCalls记录宿主提交峰值，peakMcpConcurrency是将该值按8截断的上界，不能当作服务侧实测峰值；本文使用配置上限描述并发。融合早期记录的 externalLlmRequests 继承执行阶段计数，完整模型往返统一以 requests.length/modelRequests 为准。\n\n安装及离线验证：\n\n\`\`\`powershell\ncd demo\nnode setup-coding.mjs\nnode verify-coding-fixture.mjs\nnode coding-matrix.mjs # 使用本机.env.local，真实在线调用，会消耗API用量\ncd ..\nnode scripts/verify-coding.mjs\n\`\`\`\n\n实现：[项目和验收器](demo/coding-fixture.mjs)、[共同MCP服务](demo/coding-mcp-server.mjs)、[Pi编码路径](demo/coding-pi.mjs)、[官方PTC编码路径](demo/coding-ptc.mjs)、[融合交接](demo/coding-hybrid.mjs)、[实验运行器](demo/coding-matrix.mjs)。附件：[逐次CSV](results/coding/metrics.csv)、[聚合及范围](results/coding/summary.json)、[全部记录及SHA256](results/coding/manifest.json)。验收脚本会在新的临时目录重建最终源码，重新编译并运行行为测试，还会根据真实补丁调用重放文件修改，核对初始快照、受保护文件、API usage和交接请求。此前订单与融合证据保持原样。\n`;
await writeFile(new URL('docs/coding-article.md',root),text.replaceAll('(demo/','(../demo/').replaceAll('(results/','(../results/'));
console.log(JSON.stringify({tasks:27,passed,calibration:m.priorAttempts.length,winners}));
