import {readFile,writeFile} from 'node:fs/promises';
const root=new URL('../',import.meta.url),base=new URL('results/hybrid/',root);
const m=JSON.parse(await readFile(new URL('manifest.json',base),'utf8'));
if(m.runs.length!==81||!m.runs.every(r=>r.passed))throw Error('Hybrid continuation not complete');
const median=a=>[...a].sort((a,b)=>a-b)[Math.floor(a.length/2)];
const fields=['inputTokens','outputTokens','cacheHitTokens','modelRequests','localWallMs','modelWallMs','initialSdkDeclarationBytes','surfacedResultBytes'];
const groups=m.orders.flatMap(count=>m.tools.flatMap(toolCount=>m.paths.map(mode=>{
 const rows=m.runs.filter(r=>r.count===count&&r.toolCount===toolCount&&r.mode===mode);
 return {count,toolCount,mode,revisions:rows.map(r=>r.revision??'hybrid-v1'),medians:Object.fromEntries(fields.map(f=>[f,median(rows.map(r=>r.metrics[f]))]))};
})));
await writeFile(new URL('summary.json',base),JSON.stringify({tasks:81,passed:81,priorAttempts:m.priorAttempts.length,aggregation:'cell median of three successful retained tasks; discovery prompt revisions are mixed, failures separately retained',groups},null,2));
await writeFile(new URL('metrics.csv',base),['id,count,toolCount,repeat,mode,revision,'+fields.join(','),...m.runs.map(r=>[r.id,r.count,r.toolCount,r.repeat,r.mode,r.revision??'hybrid-v1',...fields.map(f=>r.metrics[f]??'')].join(','))].join('\n')+'\n');
const get=(o,t,p)=>groups.find(g=>g.count===o&&g.toolCount===t&&g.mode===p).medians;
const rows=m.orders.flatMap(o=>m.tools.map(t=>{const c=get(o,t,'codemode'),p=get(o,t,'ptc'),h=get(o,t,'hybrid');return `| ${o} / ${t} | ${c.inputTokens} / ${p.inputTokens} / ${h.inputTokens} | ${c.localWallMs} / ${p.localWallMs} / ${h.localWallMs} |`;}));
const savings=m.orders.map(o=>100*(1-get(o,60,'hybrid').inputTokens/get(o,60,'ptc').inputTokens));
const faster=m.orders.flatMap(o=>m.tools.map(t=>get(o,t,'hybrid').localWallMs<get(o,t,'ptc').localWallMs)).filter(Boolean).length;
const cFaster=m.orders.flatMap(o=>m.tools.map(t=>get(o,t,'hybrid').localWallMs<get(o,t,'codemode').localWallMs)).filter(Boolean).length;
const revisions=Object.entries(m.runs.filter(r=>r.mode==='hybrid').reduce((out,r)=>{const key=r.revision??'hybrid-v1';out[key]=(out[key]??0)+1;return out;},{})).map(([key,n])=>key+': '+n+'次').join('；');
const priorKinds={};for(const r of m.priorAttempts){const type=r.metrics.inputTokens==null?'no API usage / transport or local failure':'online discovery failure';priorKinds[type]=(priorKinds[type]??0)+1;}
const text=`\n## 补充：先发现，再生成 SDK，交给 PTC\n\nCodemode 的按需发现和 PTC 的程序执行可以组合。首轮只提供 Codemode 入口，模型写一段发现代码，在运行时检索接口，返回所需工具名。宿主拿这些名字查询工具注册表，取出权威的描述、输入和输出 JSON Schema，只注册选中的工具，再由 Harness 官方生成器生成 TypeScript SDK。下一轮提供 run_code 和这份小 SDK，模型编写业务代码，执行结束后再生成回答。\n\n注册表可以理解为 \`工具名 → {description, inputSchema, outputSchema, execute}\`。查表、SDK 类型转换和运行时绑定都是确定性的宿主操作，**转换阶段没有额外 LLM 请求**。SDK 是接口声明和调用绑定，不是现场编译一个 npm 包。实际调用仍经 MCP bridge 访问同一个服务。\n\n本实现由 Pi 完成发现，再由宿主把真实用户消息、模型的 Codemode 调用和发现结果接入 Harness 请求，执行阶段使用官方 Node PTC。两套框架有显式交接，也有各自的初始化成本；这不是 Harness 内部原生的一条统一 Agent loop。首轮只有 codemode，后续只有 run_code。发现阶段不执行业务，执行阶段只注册实际选出的三个工具，不通过宿主补选来纠正模型。原始请求体保存在证据里的 wirePayload。\n\n### 本次补充结果\n\n此前108次四路径矩阵保持原样。本次另设三路径的81个任务：3种订单数 × 3种工具数 × Codemode/PTC/融合 × 3次重复。暂停前已成功的38个任务全部保留，没有重跑；本次只续跑缺失或失败任务。最终81个任务全部通过业务事实和执行过程核验。\n\n**重要口径：这是带校准过程的续跑结果。** 成功的融合记录包含早期发现提示和修正后的提示；不是同一最终提示下重新跑出的27次实验。融合成功记录的版本分布为${revisions}。早期失败是代码分别搜索三个能力、按描述关键词或首条命中选取时，重复选中了订单列表。最终协议改为一次组合检索返回三个不同接口，模型仍自行生成发现代码，没有硬编码工具名。另有本次受网络执行权限限制、无 API usage 的失败；这些记录也保留。历史失败总计${m.priorAttempts.length}条：${priorKinds["online discovery failure"]??0}次在线发现失败、${priorKinds["no API usage / transport or local failure"]??0}次无API用量的网络或本地失败。失败开销未加入下表成功任务的中位数，不代表包含重试的生产成本。\n\n每格列出三次成功任务的中位数，顺序均为 **Codemode / PTC / 融合**。input token 包含缓存命中；耗时包含在线推理和本地初始化。\n\n| 订单数 / 工具数 | API 输入 token | 端到端耗时 ms |\n|---|---:|---:|\n${rows.join('\n')}\n\n**融合保留了按需接口暴露的优势，但没有自动获得 PTC 的两轮延迟。** 本次三个业务接口的 SDK 在所有工具规模下均为3504字节；全量 PTC 的 SDK 随目录从3504增长到9538、26458字节。60个工具时，融合相比全量PTC少输入${Math.min(...savings).toFixed(1)}%–${Math.max(...savings).toFixed(1)}%。不过融合通常仍需“发现、编排、总结”三轮；九格中全量PTC的耗时中位数均低于融合；融合在${cFaster}格低于纯Codemode。**当前结果支持用融合控制大工具目录的输入规模，不能据此把它称为最快路径，也不能据此保证比纯Codemode更省。**\n\n发现结果会作为历史再次进入后续请求，所以只生成小 SDK 不等于零发现成本。发现代码、结果、SDK和历史都计入 API 输入。不同发现提示、缓存状态、两套框架初始化，以及 Codemode 和 PTC 不同的并发上限，仍会影响结果。这里没有做独立冷缓存、同并发上限或跨模型测试。\n\n### 复现与证据\n\n实现：[融合交接](demo/hybrid.mjs)、[发现阶段](demo/engine.mjs)、[选中接口注册与 SDK 生成](demo/ptc.mjs)、[续跑器](demo/hybrid-matrix.mjs)。在配置好的 demo 目录运行 \`node hybrid-matrix.mjs\`；运行器跳过已成功任务，失败尝试写入独立附件，不覆盖旧证据，会消耗在线 API 用量。\n\n公开附件：[逐次指标](results/hybrid/metrics.csv)、[聚合数据](results/hybrid/summary.json)、[全部尝试及 SHA256](results/hybrid/manifest.json)。在仓库根目录运行 \`node scripts/verify-hybrid.mjs\`，核对事实、调用集合、SDK大小、实际请求交接、API usage和附件哈希。Hybrid 根级 initialSdkDeclarationBytes 指首次 **PTC执行阶段** SDK；首轮发现没有该 SDK。根级 accumulatedRequestBytes 来自框架内部上下文，交接后的实际网络请求以 wirePayload/wireRequestBytes 为准。未修改原始采集指标。\n`;
await writeFile(new URL('docs/hybrid-article.md',root),text.replaceAll('(demo/','(../demo/').replaceAll('(results/','(../results/'));
console.log(JSON.stringify({tasks:81,prior:m.priorAttempts.length,hybridFasterThanPtc:faster,hybridFasterThanCodemode:cFaster,savings60:savings}));
